// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTdva2L7ofrImgJ3OmFwskWEZqaZbuRoE',
    appId: '1:802670210215:web:cedfff9cba00c3d798bf82',
    messagingSenderId: '802670210215',
    projectId: 'mynotes-zynext',
    authDomain: 'mynotes-zynext.firebaseapp.com',
    storageBucket: 'mynotes-zynext.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIYcfcYVWd8hfM1W0-l3GvKg39Ic5dYAk',
    appId: '1:802670210215:android:9f6d5ec40019df5198bf82',
    messagingSenderId: '802670210215',
    projectId: 'mynotes-zynext',
    storageBucket: 'mynotes-zynext.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlK3EeLEkv5fGlPOvVk9jepd0Q0zCTnRk',
    appId: '1:802670210215:ios:1e26742b0251b6ad98bf82',
    messagingSenderId: '802670210215',
    projectId: 'mynotes-zynext',
    storageBucket: 'mynotes-zynext.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlK3EeLEkv5fGlPOvVk9jepd0Q0zCTnRk',
    appId: '1:802670210215:ios:1e26742b0251b6ad98bf82',
    messagingSenderId: '802670210215',
    projectId: 'mynotes-zynext',
    storageBucket: 'mynotes-zynext.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTdva2L7ofrImgJ3OmFwskWEZqaZbuRoE',
    appId: '1:802670210215:web:68d702b2ae553f3998bf82',
    messagingSenderId: '802670210215',
    projectId: 'mynotes-zynext',
    authDomain: 'mynotes-zynext.firebaseapp.com',
    storageBucket: 'mynotes-zynext.appspot.com',
  );
}
